//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RG2System_Garage.Viwer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RG2System_Garage.Viwer.Resources.MSG", typeof(MSG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro {0} com sucesso!!.
        /// </summary>
        internal static string CADASTRO_X0_COM_SUCESSO {
            get {
                return ResourceManager.GetString("CADASTRO_X0_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionado um {0} para prosseguir..
        /// </summary>
        internal static string E_NECESSARIO_SELECIONAR_UM_X0_PARA_PROSSEGUIR {
            get {
                return ResourceManager.GetString("E_NECESSARIO_SELECIONAR_UM_X0_PARA_PROSSEGUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionado uma {0} para prosseguir..
        /// </summary>
        internal static string E_NECESSARIO_SELECIONAR_UMA_X0_PARA_PROSSEGUIR1 {
            get {
                return ResourceManager.GetString("E_NECESSARIO_SELECIONAR_UMA_X0_PARA_PROSSEGUIR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao consultar dados..
        /// </summary>
        internal static string ERRO_AO_CONSULTAR_DADOS {
            get {
                return ResourceManager.GetString("ERRO_AO_CONSULTAR_DADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao listar {0}.
        /// </summary>
        internal static string ERRO_AO_LISTA_X0 {
            get {
                return ResourceManager.GetString("ERRO_AO_LISTA_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao selecionar {0}.
        /// </summary>
        internal static string ERRO_AO_SELECIONAR_X0 {
            get {
                return ResourceManager.GetString("ERRO_AO_SELECIONAR_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao realizar procedimento, tente novamente!.
        /// </summary>
        internal static string ERRO_REALIZAR_PROCEDIMENTO {
            get {
                return ResourceManager.GetString("ERRO_REALIZAR_PROCEDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão realizada com sucesso..
        /// </summary>
        internal static string EXCLUSAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("EXCLUSAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        internal static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} realizada com sucesso!.
        /// </summary>
        internal static string X0_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} realizado com sucesso!.
        /// </summary>
        internal static string X0_REALIZADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_REALIZADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} salvo com sucesso!.
        /// </summary>
        internal static string X0_SALVO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_SALVO_COM_SUCESSO", resourceCulture);
            }
        }
    }
}
